projects:
  todoamplify:
    schemaPath: amplify/backend/api/todoamplify/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/api.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
